// Generated by PMS #552
package cfw

import (
	"context"
	"strings"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/go-uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/tidwall/gjson"

	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/httphelper"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/schemas"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/utils"
)

func DataSourceCfwDomainNameIdParseIpList() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceCfwDomainNameIdParseIpListRead,

		Schema: map[string]*schema.Schema{
			"region": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: `Specifies the region in which to query the resource. If omitted, the provider-level region will be used.`,
			},
			"fw_instance_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the Firewall ID.`,
			},
			"domain_set_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the domain name group ID.`,
			},
			"domain_address_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the domain name ID.`,
			},
			"address_type": {
				Type:        schema.TypeInt,
				Optional:    true,
				Description: `Specifies the address type.`,
			},
			"enterprise_project_id": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `Specifies the Enterprise project ID.`,
			},
			"data": {
				Type:        schema.TypeList,
				Computed:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Description: `The IP address resolution data of a domain name.`,
			},
		},
	}
}

type DomainNameIdParseIpListDSWrapper struct {
	*schemas.ResourceDataWrapper
	Config *config.Config
}

func newDomainNameIdParseIpListDSWrapper(d *schema.ResourceData, meta interface{}) *DomainNameIdParseIpListDSWrapper {
	return &DomainNameIdParseIpListDSWrapper{
		ResourceDataWrapper: schemas.NewSchemaWrapper(d),
		Config:              meta.(*config.Config),
	}
}

func dataSourceCfwDomainNameIdParseIpListRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	wrapper := newDomainNameIdParseIpListDSWrapper(d, meta)
	listDomainParseIpRst, err := wrapper.ListDomainParseIp()
	if err != nil {
		return diag.FromErr(err)
	}

	id, err := uuid.GenerateUUID()
	if err != nil {
		return diag.FromErr(err)
	}
	d.SetId(id)

	err = wrapper.listDomainParseIpToSchema(listDomainParseIpRst)
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}

// @API CFW GET /v1/{project_id}/domain/parse-ip-list/{domain_address_id}
func (w *DomainNameIdParseIpListDSWrapper) ListDomainParseIp() (*gjson.Result, error) {
	client, err := w.NewClient(w.Config, "cfw")
	if err != nil {
		return nil, err
	}

	uri := "/v1/{project_id}/domain/parse-ip-list/{domain_address_id}"
	uri = strings.ReplaceAll(uri, "{domain_address_id}", w.Get("domain_address_id").(string))
	params := map[string]any{
		"address_type":          w.Get("address_type"),
		"domain_set_id":         w.Get("domain_set_id"),
		"fw_instance_id":        w.Get("fw_instance_id"),
		"enterprise_project_id": w.Get("enterprise_project_id"),
	}
	params = utils.RemoveNil(params)
	return httphelper.New(client).
		Method("GET").
		URI(uri).
		Query(params).
		Request().
		Result()
}

func (w *DomainNameIdParseIpListDSWrapper) listDomainParseIpToSchema(body *gjson.Result) error {
	d := w.ResourceData
	mErr := multierror.Append(nil,
		d.Set("region", w.Config.GetRegion(w.ResourceData)),
		d.Set("data", body.Get("data").Value()),
	)
	return mErr.ErrorOrNil()
}
